<div style="border: 4px solid #dfdfdf; overflow: hidden; height: 510px; padding: 5px;">
	<div style="width:100%;height:500px;overflow:auto;margin:0;padding:3px;background:black;color:#fff;
         font:normal 11px Lucida Console, Courier New, serif;">
		
		<?php
			$blockObj= $block->getLayout()->createBlock('Hiecor\PaymentMethod\Block\Index');
			echo $blockObj->getMyCustomMethod();
		?>
	</div>
</div>